### ISSUE TITLE
Saying hello

### ISSUE THREAD

**Issue by cetanu** [danielgtaylor/python-betterproto#15]
Howdy.

I worked on a [project](https://pypi.org/project/envoy-data-plane/) today, and noticed I am the first ["dependent"](https://github.com/danielgtaylor/python-betterproto/network/dependents) for your package. So I thought I would just say hi.

I really appreciate the effort put in to make protocol buffers represented as Python objects in a way that isn't a complete mess.

Thanks for your work. I might pop around some time if I can contribute some kind of improvement.

💟

**Comment by danielgtaylor** [comment]
Glad to hear you find it useful! Thanks for reaching out! :+1:
