### ISSUE TITLE
Can't auto generate the import from multiple files.

### ISSUE THREAD

**Issue by wildfire810** [danielgtaylor/python-betterproto#155]
For example,
In PlatformStruct.proto file,
```protobuf
syntax = "proto3";
import "QOperation.proto";
```
Generated two files:
PlatformStruct.py
QOperation.py

But in PlatformStruct.py, there is not any import from QOperation.py
```python
from dataclasses import dataclass
from typing import Dict, List

import betterproto
```
Error:
```
NameError: name 'FixedGate' is not defined
```
I think it need
```python
from .QOperation import FixedGate
```

**Comment by Gobot1234** [comment]
What version are you on as this should have been fixed.

**Comment by wildfire810** [comment]
betterproto[compiler]==1.2.5

**Comment by nat-n** [comment]
@wildfire810 could you try  `betterproto[compiler]==v2.0.0-beta1` ?

**Comment by wildfire810** [comment]
![image](https://user-images.githubusercontent.com/17704611/96703430-6a6dd500-13c5-11eb-97b9-926fe0b5db43.png)
![image](https://user-images.githubusercontent.com/17704611/96703513-83768600-13c5-11eb-8460-f6c414c64bf3.png)
betterproto                   2.0.0b1

**Comment by wildfire810** [comment]
only one file, using v2.0.0-beta1
It's ok
