### ISSUE TITLE
parse data will change enum value type from enum to int

### ISSUE THREAD

**Issue by wildfire810** [danielgtaylor/python-betterproto#169]
data = bytes(circuitLine)
                ret = PBCircuitLine().parse(data)  # type: 'PBCircuitLine'

circuitLine:
![image](https://user-images.githubusercontent.com/17704611/97098538-f5e2b100-16b8-11eb-810d-890682d80371.png)
ret:
![image](https://user-images.githubusercontent.com/17704611/97098545-0430cd00-16b9-11eb-95ea-e6f7cf6005fb.png)

**Comment by upcFrost** [comment]
I think it's duplicate for https://github.com/danielgtaylor/python-betterproto/issues/157
