### ISSUE TITLE
Enum Prefix is not stripped

### ISSUE THREAD

**Issue by bschug** [danielgtaylor/python-betterproto#174]
According to the [Style Guide](https://developers.google.com/protocol-buffers/docs/style#enums), protobuf enums should have the enum name as a prefix for all enum values, to avoid naming conflicts in languages like C, where all values from all enums are in the global namespace. Protobuf compilers for languages with scoped enums like C# will [strip these prefixes](https://developers.google.com/protocol-buffers/docs/reference/csharp-generated#enum) if they match the enum name. Since enums in betterproto are scoped as well, these prefixes should be stripped.

Example:
```
enum ArithmeticOperator {
    ARITHMETIC_OPERATOR_NONE = 0;
    ARITHMETIC_OPERATOR_PLUS = 1;
    ARITHMETIC_OPERATOR_MINUS = 2;
}
```
should become
```
class ArithmeticOperator(betterproto.Enum):
    NONE = 0
    PLUS = 1
    MINUS = 2
```
so that we can use it as 
```
if something.operator == ArithmeticOperator.PLUS:
     do_addition()
```
instead of
```
if something.operator == ArithmeticOperator.ARITHMETIC_OPERATOR_PLUS:
    do_addition()
```

**Comment by Gobot1234** [comment]
I'm happy to make a PR for this

**Comment by Gobot1234** [comment]
This should be fixed by #187 :)

**Comment by cigani** [comment]
This his a huge deal for my team. Can we have an ETA?

**Comment by Gobot1234** [comment]
Should be soon hopefully I just needed a re-review from Nat.

**Comment by StFS** [comment]
I'm noticing that the prefix is stripped now... but I have the question, is there any way to actually get the full enum name as defined in the .proto file via the betterproto python data classes?

**Comment by StFS** [comment]
Nevermind... I found this:
https://github.com/danielgtaylor/python-betterproto/pull/589
