### ISSUE TITLE
Empty strings are stripped serializing a repeated string field

### ISSUE THREAD

**Issue by mydatamodels** [danielgtaylor/python-betterproto#206]
Minimal test case attached.

Input data: `["0", "", "", "", "4"]`

betterproto: `b'\n\x010\n\x014'`

protoc: `b'\n\x010\n\x00\n\x00\n\x00\n\x014'`

Thanks and best regards.

[betterproto.tar.gz](https://github.com/danielgtaylor/python-betterproto/files/5911108/betterproto.tar.gz)

**Comment by wildfire810** [comment]
me too.
if it is default value

**Comment by mydatamodels** [comment]
https://github.com/danielgtaylor/python-betterproto/pull/180 fixes this as well, I'm closing this one
