### ISSUE TITLE
Example in docs doesn't work

### ISSUE THREAD

**Issue by badge** [danielgtaylor/python-betterproto#207]
From the README:

> This project also produces server-facing stubs that can be used to implement a Python gRPC server. To use them, simply subclass the base class in the generated files and override the service methods:

But running `proto -I . --python_betterproto_out=lib echo.proto` results in an `echo.py` file without an `EchoBase` class in it.

**Comment by Gobot1234** [comment]
Use the GitHub master version or betterproto==2.0.0b2

**Comment by nat-n** [comment]
Hi @badge, Indeed as @Gobot1234  pointed out, the readme is in sync with master bus is a bit ahead of the latest release (even the 2.0.0b2 pre-release). 

If you build betterproto from master:HEAD then it should work. Sorry for the confusion.

**Comment by giyyapan** [comment]
Hi @nat-n , looking forward to use the server implementation offered by betterptoto, when will this version (generates `EchoBase` class) out officially?

**Comment by Gobot1234** [comment]
V2 b2 is already on PyPi. Hopefully a full release of V2 should be out soon?

**Comment by badge** [comment]
Hi @nat-n, I've:

- Created a clean venv
- Cloned the repo and switched to the `release/2.0.0b3` branch
- Run
  - `poetry install`
  - `poe generate`
  - `poe test`

pytest fails with:

```shell
===================================================================================================================================================== ERRORS =====================================================================================================================================================
_____________________________________________________________________________________________________________________ ERROR collecting tests/inputs/example_service/test_example_service.py ______________________________________________________________________________________________________________________
ImportError while importing test module '/home/gbmb12/wd/repos/prototest/python-betterproto/tests/inputs/example_service/test_example_service.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/inputs/example_service/test_example_service.py:6: in <module>
    from tests.output_betterproto.example_service.example_service import (
E   ImportError: cannot import name 'TestBase' from 'tests.output_betterproto.example_service.example_service' (/home/gbmb12/wd/repos/prototest/python-betterproto/tests/output_betterproto/example_service/example_service/__init__.py)
```
 
So it's also failing to generate the correct `__init__.py` file with a `TestBase` class in it.

The output of `pip show betterproto` is:

```shell
Name: betterproto
Version: 2.0.0b3
Summary: A better Protobuf / gRPC generator & library
Home-page: https://github.com/danielgtaylor/python-betterproto
Author: Daniel G. Taylor
Author-email: danielgtaylor@gmail.com
License: MIT
Location: /home/gbmb12/wd/repos/prototest/.env/lib/python3.7/site-packages
Requires: grpclib
Required-by: 
```

**Comment by badge** [comment]
Working! Thanks @nat-n, @Gobot1234!

**Comment by giyyapan** [comment]
Hi, @Gobot1234 , I'm already using the 2.0.0b2 version installed via pip with --pre argument, (and I verified the version with `pip list`)but the generated file still not having the `Base` class. I haven't try building betterproto from master:HEAD, did I miss anything?

I tried both `python -m grpc_tools.protoc --proto_path . --python_out=. --python_betterproto_out=rpc rpc/*.proto`, and `protoc --proto_path . --python_out=. --python_betterproto_out=rpc rpc/*.proto`, neither of them generates the `Base` classes.

Thank you!

FYI: The generated file is already under the new structure (`echo/__init__.py`), here is the file content:
```python
syntax = "proto3";

package echo;

message EchoRequest {
  string value = 1;
  // Number of extra times to echo
  uint32 extra_times = 2;
}

message EchoResponse {
  repeated string values = 1;
}

message EchoStreamResponse  {
  string value = 1;
}

service Echo {
  rpc Echo(EchoRequest) returns (EchoResponse);
  rpc EchoStream(EchoRequest) returns (stream EchoStreamResponse);
}
```

**Comment by lllfx** [comment]
> Hi, @Gobot1234 , I'm already using the 2.0.0b2 version installed via pip with --pre argument, (and I verified the version with `pip list`)but the generated file still not having the `Base` class. I haven't tried building betterproto from master:HEAD, did I miss anything?
> 
> I tried both `python -m grpc_tools.protoc --proto_path . --python_out=. --python_betterproto_out=rpc rpc/*.proto`, and `protoc --proto_path . --python_out=. --python_betterproto_out=rpc rpc/*.proto`, neither of them generates the `Base` classes.
> 
> Thank you!
> 
> FYI: The generated file is already under the new structure (`echo/__init__.py`), here is the file content:
> 
> ```python
> # Generated by the protocol buffer compiler.  DO NOT EDIT!
> # sources: rpc/echo.proto
> # plugin: python-betterproto
> from dataclasses import dataclass
> from typing import AsyncIterator, List
> 
> import betterproto
> import grpclib
> 
> 
> @dataclass(eq=False, repr=False)
> class EchoRequest(betterproto.Message):
>     value: str = betterproto.string_field(1)
>     # Number of extra times to echo
>     extra_times: int = betterproto.uint32_field(2)
> 
>     def __post_init__(self) -> None:
>         super().__post_init__()
> 
> 
> @dataclass(eq=False, repr=False)
> class EchoResponse(betterproto.Message):
>     values: List[str] = betterproto.string_field(1)
> 
>     def __post_init__(self) -> None:
>         super().__post_init__()
> 
> 
> @dataclass(eq=False, repr=False)
> class EchoStreamResponse(betterproto.Message):
>     value: str = betterproto.string_field(1)
> 
>     def __post_init__(self) -> None:
>         super().__post_init__()
> 
> 
> class EchoStub(betterproto.ServiceStub):
>     async def echo(self, *, value: str = "", extra_times: int = 0) -> "EchoResponse":
> 
>         request = EchoRequest()
>         request.value = value
>         request.extra_times = extra_times
> 
>         return await self._unary_unary("/echo.Echo/Echo", request, EchoResponse)
> 
>     async def echo_stream(
>         self, *, value: str = "", extra_times: int = 0
>     ) -> AsyncIterator["EchoStreamResponse"]:
> 
>         request = EchoRequest()
>         request.value = value
>         request.extra_times = extra_times
> 
>         async for response in self._unary_stream(
>             "/echo.Echo/EchoStream",
>             request,
>             EchoStreamResponse,
>         ):
>             yield response
> ```

betterproto==2.0.0b3
