### ISSUE TITLE
Enhanchement: Add "troubleshooting" section to the documentation

### ISSUE THREAD

**Issue by ShayNehmad-RecoLabs** [danielgtaylor/python-betterproto#224]
After a discussion on Slack with an issue I had, @nat-n and I discussed adding a troubleshooting section to the docs:

![image](https://user-images.githubusercontent.com/70973922/113434516-c82d3100-93e9-11eb-85ce-32cfd72c4305.png)

[Slack link](https://betterproto.slack.com/archives/C014C74KU7N/p1617365727009000)

So I'm opening this issue to correlate to the PR I'm about to open :smile_cat:

**Comment by nat-n** [comment]
Closing this issue in favour of the PR.
