### ISSUE TITLE
proto3 support for optional

### ISSUE THREAD

**Issue by SoerenBusse** [danielgtaylor/python-betterproto#229]
Proto3 supports the optional keyword. All libraries supporting this keyword needs to indicate this explicitly. Otherwise the complication will fail with `is a proto3 file that contains optional fields, but code generator protoc-gen-python_betterproto hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.`

Would it be possible to enable proto3 optional?

See this issue for more detail: https://github.com/vmagamedov/grpclib/issues/125

**Comment by nat-n** [comment]
Thanks for bringing this up. Looks like this was quite recently added as a fully supported feature: https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0

This is kinda of a significant change to proto3 semantics, and will take a bit of thought about how to best adapt the API to support it. It doesn't look like the official proto3 guide has been updated to reflect this yet, but I found this guide which looks highly relevant: https://chromium.googlesource.com/external/github.com/protocolbuffers/protobuf/+/refs/heads/master/docs/implementing_proto3_presence.md

Updating the Message metadata model to support this should allow the removal of this hack in the plugin: https://github.com/danielgtaylor/python-betterproto/blob/95339bf74d774bb57a55a73167d94bd5e44df439/src/betterproto/plugin/models.py#L119

**Comment by marianhlavac** [comment]
Is there any progess on this? It's currently very important feature for us, and we're forced to use official python protoc plugin for now.

**Comment by kalzoo** [comment]
My comment on #35 would have made more sense here - the quick-fix might be to just treat `optional` fields as single-variant `oneof` to unblock parsing definitions which include it.

**Comment by jdlourenco** [comment]
Are there any news on this?

**Comment by Gobot1234** [comment]
Yes this is nearly ready but there is an issue with the fields recursing infinitely https://github.com/danielgtaylor/python-betterproto/pull/281

**Comment by jdlourenco** [comment]
@Gobot1234  are tests only failing on the pipeline? I ran `poe test` and `poetry run pytest tests/` locally and they ran successfully.

**Comment by Gobot1234** [comment]
I'm not entirely sure what's up with it, @kalzoo is the person you should be asking if you'd be willing to do some debugging and provide a fix for the failing tests it will get merged and then beta 4 can be shipped with support for this.

**Comment by Gobot1234** [comment]
v.2.0.0b4 has just been released and includes support for this.

**Comment by atulsriv** [comment]
This is gonna be a long shot, but I am still seeing this error. I am on version of v.2.0.0b6, I have libprotoc 3.21.9. It should be working for me, but I still run into this error. been stuck for a few days, so if anyone has any ideas please lmk thanks

**Comment by seansica** [comment]
Issue still occurring.

Error:
```
src/foo/bar/message.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-python_betterproto hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.
```

`pyproject.yaml`:
```
protobuf = "^5.29.2"
betterproto = {extras = ["compiler"], version = "^1.2.5"}
```
```
❯ poetry run python -m pip list | grep proto
betterproto        1.2.5
mypy-protobuf      3.6.0
protobuf           5.29.2
types-protobuf     5.29.1.20241207
❯ poetry run python --version
Python 3.11.9
```

Relevant snippet of `.proto` file:
```
message Foo {
  // ..
  optional string foo = 45;
  // ...
  optional bool bar = 49;
}
```

**Comment by Gobot1234** [comment]
Use 2.0.0b6 please

**Comment by seansica** [comment]
> Use 2.0.0b6 please

Thanks, that appears to work
