### ISSUE TITLE
Compilation of nested packages creates unimportable modules

### ISSUE THREAD

**Issue by ziima** [danielgtaylor/python-betterproto#237]
I encountered an error when using nested packages with basic message on upper level. Example:
```proto
# base.proto
syntax = "proto3";

package Foo;

message Bar {
    string value = 1;
}
```
```proto
# example.proto
syntax = "proto3";

import "base.proto";

package Foo.Example;

message Example {
    Bar value = 1;
}
```
Compilation:
```
$ protoc -I . --python_betterproto_out=. base.proto example.proto 
Writing Foo.py
Writing Foo/Example.py
Writing Foo/__init__.py
Writing __init__.py
```
The result contains a clear clash in python module names, the `Foo/__init__.py` takes precedence over `Foo.py`, and thus `Foo.Bar` can't be imported at all.

I suggest to put the contents of `Foo.py` into `Foo/__init__.py` (it's not nice, I know) to allow these construction of packages possible.

**Comment by nat-n** [comment]
Hi @ziima, thanks for reporting this. 

Which version of of protobuf are you using? I think this might have been fixed in the 2.0.0 beta.

**Comment by ziima** [comment]
I'm running 1.2.5.

**Comment by ziima** [comment]
OK, I tried 2.0.0b3 and it's working there. :+1:
