### ISSUE TITLE
Issue with `parse` on PBF response.  Misses Data.

### ISSUE THREAD

**Issue by achapkowski** [danielgtaylor/python-betterproto#247]
Hello,

I have a set of dataclasses defined as such:

```

@dataclass
class GraphQueryResultHeader(betterproto.Message):
    minor_version: int = betterproto.uint32_field(1)
    data_model_timestamp: int = betterproto.uint64_field(2)
    transform: "EsriTypesTransform" = betterproto.message_field(3)
    error: "Error" = betterproto.message_field(4)
    field_names: List[str] = betterproto.string_field(5)
    compressed_frames: bool = betterproto.bool_field(6)


@dataclass
class GraphQueryRow(betterproto.Message):
    values: List["AnyValue"] = betterproto.message_field(1)


@dataclass
class GraphQueryResultFrame(betterproto.Message):
    error: "Error" = betterproto.message_field(1)
    rows: List["GraphQueryRow"] = betterproto.message_field(2)

```

and when I go and parse from the response, I can get back the `GraphQueryResultHeader`, but the `GraphQueryResultFrame` is always empty.

Attached is a zip of a response with one record.  Any ideas why `rows` isn't deserializing?

### Code to Reproduce:

```python
with open(r"<path to data>", 'rb') as reader:
     data = reader.read()
     frame =  GraphQueryResultFrame().parse(data)
     print(frame.rows) # always == 0 rows, should be 1 row.
```

Is there an issue with `List` types?

[query_response.zip](https://github.com/danielgtaylor/python-betterproto/files/6672377/query_response.zip)

**Comment by Gobot1234** [comment]
Does this response correctly parse with google's protobuf implementation?

**Comment by achapkowski** [comment]
@Gobot1234 it does parse, still missing records.  I believe the proto file was incorrect.  Thank you
