### ISSUE TITLE
Plugin failed with status code 1

### ISSUE THREAD

**Issue by FHTMitchell** [danielgtaylor/python-betterproto#269]
I'm getting the following error

```
--python_betterproto_out: protoc-gen-python_betterproto: Plugin failed with status code 1.
```

 when running the following script

```bash
#!/usr/bin/env bash

SRC=$1
OUT=$2
mkdir -p $OUT

python -m grpc_tools.protoc \
         -I $SRC \
         $SRC/vol/* \
         --python_betterproto_out=$OUT
```

This works absolutely fine with other plugins such as `grpclib`.

Here is my pip freeze

```
$ pip freeze
betterproto==1.2.5
grpcio==1.40.0
grpcio-tools==1.40.0
grpclib==0.4.2
h2==4.0.0
hpack==4.0.0
hyperframe==6.0.1
multidict==5.1.0
protobuf==3.18.0
six==1.16.0
stringcase==1.2.0

$ python --version
Python 3.9.7
```

I have tried with a few other environments too, all with the same error.

**Comment by Gobot1234** [comment]
Can you try with 2.0.0b3 and also could you show us the proto files you are trying to generate code from?

**Comment by FHTMitchell** [comment]
Same result with 2.0.0b3 and my proto.file is just this for now

```proto
syntax = "proto3";

package vol.fx;

import "google/protobuf/timestamp.proto";

service FxService {
	rpc RunFxPipeline (FxRequest) returns (FxResponse);
}

message FxRequest {
  google.protobuf.Timestamp as_of_time = 1;
  Cross cross = 2;
}

message Cross {
  string base_ccy = 1;
  string counter_ccy = 2;
}

message FxRate {
  Cross cross = 1;
  double rate = 2;
}

message FxResponse {
  repeated FxRate fx = 1;
}
```

**Comment by FHTMitchell** [comment]
Is there any update on this? Seems I'm not the only one #270

**Comment by Gobot1234** [comment]
What protoc version do you have, I'm on 3.17.1 and it seems to compile fine for me.

**Comment by FHTMitchell** [comment]
```
$ protoc --version
libprotoc 3.17.1
```

Tried on 3.16.0 too

**Comment by FHTMitchell** [comment]
Is there a way to get verbose debugging logs or something?

**Comment by Gobot1234** [comment]
Oh I just realised I've been using protoc to compile not grpc_tools. I'll try with that.

**Comment by FHTMitchell** [comment]
> I had the same problem in conda environment. The reason why it does not work is extra dependency of betterproto. If you do below pip command (as mentioned in the Installation section), I think it will work..
> 
> ```
> pip install "betterproto[compiler]"
> ```
> 
> It seems that it also works if you only install "black" and "jinja2"

That did indeed fix the issue!!
