### ISSUE TITLE
Feature request: Python 3.6 support

### ISSUE THREAD

**Issue by Minyus** [danielgtaylor/python-betterproto#27]
As some systems still use Python 3.6, I'd like to request (partial) support for Python 3.6.

**Comment by nat-n** [comment]
This would be great for all the poor folks writing code for enterprise linux environments, which are always a version or two behind.

**Comment by nat-n** [comment]
This could be closed given a minor version bump and release to PyPI?

**Comment by Minyus** [comment]
Yes. Thanks!
