### ISSUE TITLE
Cannot run through example- Plugin failed with status code 1

### ISSUE THREAD

**Issue by rshanker779** [danielgtaylor/python-betterproto#270]
Hi, 
I believe I have a similar issue to this one https://github.com/danielgtaylor/python-betterproto/issues/269 but running through the example in the README.

Steps to recreate:
Fresh python 3.7 env, install pre release better proto
```
conda create -n proto_example python=3.7
conda activate proto_example
pip install --pre betterproto
```
 A `pip freeze` here gives:
```
betterproto==2.0.0b3
certifi==2021.5.30
grpclib==0.4.2
h2==4.0.0
hpack==4.0.0
hyperframe==6.0.1
multidict==5.1.0
python-dateutil==2.8.2
six==1.16.0
```

Then create example.proto:
```
syntax = "proto3";

package hello;

// Greeting represents a message you can tell a user.
message Greeting {
  string message = 1;
}
```
 and after running `mkdir lib`, run 
```
protoc -I . --python_betterproto_out=lib example.proto
```

Output at this point is 
```
--python_betterproto_out: protoc-gen-python_betterproto: Plugin failed with status code 1.
```

Some other useful debbugging info:

```
protoc --version
libprotoc 3.6.1
```

and I'm running on Ubuntu 20.04.3 on WSL2.

**Comment by Gobot1234** [comment]
Is this issue fixed @rshanker779?

**Comment by rshanker779** [comment]
Yes this works now, thanks!
