### ISSUE TITLE
Templated client service methods don't allow for pass-through of metadata

### ISSUE THREAD

**Issue by tomikazi** [danielgtaylor/python-betterproto#275]
The protected `_unary_unary`, `_stream_unary`, et al. all accept metadata to convey to the server, but the service methods generated from the template do not take an optional `metadata` parameter. If would be extremely useful if they would.

Any plans for adding this capability? If not, any objections to adding this capability?

**Comment by Gobot1234** [comment]
Sounds good to me

**Comment by dchebakov** [comment]
Is there a way to pass this parameter now?

**Comment by abn** [comment]
@dchebakov you can do that at the class level for the `ServiceStub` as the `metadata` parameter. This might not be ideal in all scenarios as sometimes you would want to set metadata per request.

**Comment by hypdeb** [comment]
Hello, I see that this is closed, but I just generated some code with `1.2.5` and the `metadata`, `timeout` and `deadline` arguments don't appear in the service methods. Do I have to pass some special argument to `protoc` for it to add those ? I also see that this change is part of the `1.2.4` release. Has it been reversed in `1.2.5` ?
