### ISSUE TITLE
Mutually recursive types recur infinitely

### ISSUE THREAD

**Issue by cpcloud** [danielgtaylor/python-betterproto#276]
The following protobuf results in infinite recursion upon construction:

```protobuf
// mutually_recursive.proto

syntax = "proto3";

message Type {
  oneof kind {
    I64 i64 = 1;
    List list_ = 2;
  }

  message I64 {}
  message List {
    Type type_ = 1;
  }
}
```

compile with:

```sh
$ protoc --python_betterproto_out=. --proto_path=. mutually_recursive.proto
```

test with:

```sh
$ python -c 'from mutually_recursive import Type; Type()'
...
RecursionError: maximum recursion depth exceeded
```

It looks like this may be happening because of default construction of every variant in a `oneof` message.

Am I doing something wrong here? Is there a way to construct this type?

**Comment by Gobot1234** [comment]
What version of betterproto are you using? If you aren't already using 2.0.0b3 you might want to give that a go using `pip install betterproto --pre`
