### ISSUE TITLE
Fix Python 3.9 CI Tasks

### ISSUE THREAD

**Issue by kalzoo** [danielgtaylor/python-betterproto#283]
Tests fail with an `ImportError` in PR #268. [Job link](https://github.com/danielgtaylor/python-betterproto/runs/4233209293?check_suite_focus=true)

Cause -> The imports are failing because the imported files don't actually exist; the previous CI task is reporting success via exit code 0 despite failure.
Cause -> Test code generation is failing with the opaque `Plugin failed with status code 1` error from `protoc`. 
Cause -> `BETTERPROTO_DUMP` doesn't produce a dumpfile because the plugin is actually failing on import. By hacking at the plugin we can reduce it to this error:

```
Unable to import `_ast3` from betterproto plugin! Please ensure that you've installed betterproto as `pip install "betterproto[compiler]"` so that compiler dependencies are included.
```

This is despite installing those dependencies with `poetry install --extras compiler` either in CI or local development.

Thus, to fix the failing tests, we should update the `black` version specification to latest. Note that this will require our minimum Python version to be upgraded to 3.6.2, which is technically a breaking change but should be within the bounds of what's acceptable for a beta release. If that's unacceptable, we can find an intervening `black` version instead.

**Comment by Gobot1234** [comment]
This was fixed wasn't it @kalzoo?
