### ISSUE TITLE
Accessing Enum name by `str()`

### ISSUE THREAD

**Issue by GalBezalel-RecoLabs** [danielgtaylor/python-betterproto#291]
Say I've compiled:
`class Priority(betterproto.Enum):`
`    PRIORITY_LOW = 0`
`    PRIORITY_MEDIUM = 1`
`    PRIORITY_HIGH = 2`

Accessing the string value of each instance (which is defined by `.toString()`) is done similarly to `Enum` class in python, via `Priority.PRIORITY_LOW.name`, for example. 

From usability point of view, I'd like to access this by the pythonic convention of `str(Priority.PRIORITY_LOW)`. (i.e. add `__str__` method to the compiled class). 

Appreciate your consideration.

**Comment by Gobot1234** [comment]
Currently betterproto.Enum does already have a dunder str method which is just inherited from enum.Enum with the 3.11(??) changes to the value of an enum's str I think this change makes sense an should be fine to include in 2.0.0 and my Enum branch.
