### ISSUE TITLE
Incompatible types in assignment

### ISSUE THREAD

**Issue by khvn26** [danielgtaylor/python-betterproto#298]
Mypy detects incorrect typing in generated service methods:

```proto
enum TestEntityType {
  UKNOWN = 0;
  SAMPLE = 1;
  VALUE = 2;
  ANOTHER = 3;
}

message TestRequest {
  string workspace_id = 1;
  TestEntityType entity_type = 2;
}

message TestResponse {
  int32 count= 1;
}

service TestService {
  rpc TestCount(TestRequest ) returns (TestResponse ) {}
}
```

```python
@dataclass(eq=False, repr=False)
class TestRequest (betterproto.Message):
    workspace_id: str = betterproto.string_field(1)
    entity_type: "TestEntityType" = betterproto.enum_field(2)   # <---- not Optional
```
```python
    async def test_count(
        self,
        *,
        workspace_id: str = "",
        entity_type: "TestEntityType " = None,  # <---- not Optional
    ) -> "TestResponse ":
        pairs = pairs or []

        request = TestRequest()
        request.workspace_id = workspace_id
        request.entity_type = entity_type

        return await self._unary_unary(
            "/com.test.TestService/TestCount",
            request,
            TestResponse ,
        )
```

The resulting typing error is: 
```sh
error: Incompatible types in assignment (expression has type "Optional[TestEntityType]", variable has type "TestEntityType")  [assignment]
```

**Comment by khvn26** [comment]
I think [this](https://github.com/danielgtaylor/python-betterproto/blob/b0a36d12e4740b64a10c8aa86e48aa05cd382f86/src/betterproto/plugin/models.py#L463) should return `None` by default if the message field isn't defined as `optional`, and in the template this case should omit the argument completely.

Additionally, fields should be sorted so the args without a default value come first.

**Comment by khvn26** [comment]
On second hand, this might be a bug. Apparently, the default value for enums should always be the first enum member.

**Comment by khvn26** [comment]
An attempt to fix this #299

**Comment by Gobot1234** [comment]
> Apparently, the default value for enums should always be the first enum member.

Where is this stated?

**Comment by khvn26** [comment]
@Gobot1234 I proceeded from [this](https://github.com/danielgtaylor/python-betterproto/blob/master/src/betterproto/plugin/models.py#L623) comment in `EnumDefinitionCompiler.default_value_string`. 

Since `EnumDefinitionCompiler` only gets applied to generate enum classes, my guess is `EnumDefinitionCompiler.default_value_string` never got called at all.

**Comment by khvn26** [comment]
It does conform with the proto3 spec (see [Default values](https://developers.google.com/protocol-buffers/docs/proto3#default)):

> For enums, the default value is the first defined enum value, which must be 0.
