### ISSUE TITLE
which_one_of is returning ('', None) for no-fields messages after deserialization

### ISSUE THREAD

**Issue by druid8** [danielgtaylor/python-betterproto#301]
There is an issue with `which_one_of` which is not working correctly when message is deserialized and group contains embedded message which has no fields inside.

Example
```
syntax = "proto3";

message Ping {
}

message Hello {
    string message = 1;
}

message Command {
   int no = 1;
   oneof command {
      Ping ping = 2;
      Hello hello = 3;
   }
}
```

```python

# don't work correctly
cmd = Command(no=0, ping=Ping())
betterproto.which_one_of(cmd, "command")
<< ('ping', Ping())    <---- as far OK
raw = bytes(cmd)
cmd_2 = Command.FromString(raw)
betterproto.which_one_of(cmd, "command")
<< ('', None)          <----- invalid, after serialization and deserialization information about set Ping() in group was lost


# in opposite to Hello command which works correctly

cmd = Command(no=0, hello=Hello(message="hello world"))
betterproto.which_one_of(cmd, "command")
<< ('hello', Hello(message='hello_world'))
raw = bytes(cmd)
cmd_2 = Command.FromString(raw)
betterproto.which_one_of(cmd, "command")
<< ('hello', Hello(message='hello_world'))

```

Python: 3.9
betterproto: 1.2.5

I assume that after deserialization it's somehow detected which subfield from group is set basing on fact which field is filled and thus `Ping` command has no fields inside it looks like empty, however I was not debugging so deep to confirm this.

**Comment by Gobot1234** [comment]
Can you try the latest version of betterproto with `pip install -U betterproto --pre`?

**Comment by druid8** [comment]
On beta version it seems to be working fine. 

I found that issue was in serialization not deserialization. In stable version the one of field is not serialized at all and missing in the binary result.

Probably can be closed.
