### ISSUE TITLE
Enum with reserved word (`None`) clashes with python

### ISSUE THREAD

**Issue by ikelos** [danielgtaylor/python-betterproto#302]
Hiya,

I've just started working with gather.town which provides a version 3 proto file.  I had to remove the optional keywords (as best I can tell, they're somewhat unnecessary in proto3 files) and it all started generating fine.  I found, however, that when importing the file that the following enum:

```
message EmoteEnum {
  enum ENUM {
    None = 0;
    Wave = 1;
    Heart = 2;
    PartyPopper = 3;
    ThumbsUp = 4;
    QuestionMark = 5;
    RaisedHand = 6;
  }
}
```

generates the following dataclass:

```
class EmoteEnumENUM(betterproto.Enum):
    None = 0
    Wave = 1
    Heart = 2
    PartyPopper = 3
    ThumbsUp = 4
    QuestionMark = 5
    RaisedHand = 6
```

which tries to assign to None.  There doesn't appear to be a great mechanism for working around this automatically.  The best I've found would be to append an `_` and documenting that this would happen to any field name found in [keyword.kwlist](https://docs.python.org/3/library/keyword.html#keyword.kwlist).  There is a [workaround](https://stackoverflow.com/questions/60074344/reserved-word-as-an-attribute-name-in-a-dataclass-when-parsing-a-json-object) for `dataclasses-json`, but obviously that's not  a default package with python and doesn't look like a suitable solution to the issue...

**Comment by Gobot1234** [comment]
This is fixed by https://github.com/danielgtaylor/python-betterproto/pull/187
