### ISSUE TITLE
Format field comments as real docstrings

### ISSUE THREAD

**Issue by michaelosthege** [danielgtaylor/python-betterproto#303]
This line https://github.com/danielgtaylor/python-betterproto/blob/master/src/betterproto/templates/template.py.j2#L49 formats the comments on class attributes like this.

With the example from the readme:
```proto
// This is the class docstring
message EchoRequest {
    string value = 1;
    // This is a field docstring
    uint32 extra_times = 2;
}
```

It generates this Python code:
```python
@dataclass
class EchoRequest(betterproto.Message):
    """This is the class docstring"""

    value: str = betterproto.string_field(1)
    # This is a field docstring
    extra_times: int = betterproto.uint32_field(2)
```

But a slightly different formatting would make it a docstring recognized by IDEs:
```python@dataclass
class EchoRequest(betterproto.Message):
    """This is the class docstring"""

    value: str = betterproto.string_field(1)
    extra_times: int = betterproto.uint32_field(2)
    """This is a field docstring"""
```
![image](https://user-images.githubusercontent.com/5894642/147353095-8332b458-474c-45b0-b156-52520c09558a.png)

Would you mind changing the formatting here? Or are there specific reasons why it produces the current output format?

**Comment by Gobot1234** [comment]
This seems to me like a good change. Would you be willing to PR it?

**Comment by michaelosthege** [comment]
I'm trying, but are blocked by unfamiliarity with the projects structure and tooling. I have no poetry installed and no experience with its workflow..
* How can I install `betterproto` it in develop mode? `pip install -e .` There's no `setup.py` in the project and I have never seen something like that.
* I tried to run the tests, but since I couldn't get it installed, also `pytest -v` from the root dir didn't work..
* Looks like the formatting of `field.comment` must be changed, but I couldn't find where that's defined.

Also it looks like some classes in the codebase are autogenerated and would be reformatted by the change.

**Comment by Gobot1234** [comment]
You should install poetry `pip install poetry` using pip is a pain, then to install you just do `poetry install`
To run the tests you need to do `poe full-test`.
field.comment is currently defined here, https://github.com/danielgtaylor/python-betterproto/blob/master/src/betterproto/plugin/models.py#L195-L202, you'd need to edit this line here https://github.com/danielgtaylor/python-betterproto/blob/671c0ff4ac77d01a1ecadb68c737aaeaeb29d874/src/betterproto/plugin/models.py#L152
