### ISSUE TITLE
Problem with inner class names

### ISSUE THREAD

**Issue by Miisakiiisakii** [danielgtaylor/python-betterproto#344]
Proto:

    message BattleEnd{
          bool is_win = 1; 
          message changed_player_exp{
              sint32 old_exp = 1; 
          }
          changed_player_exp changed_exp = 2; 
    }

gen:

    @dataclass(eq=False, repr=False)
    class BattleEnd(betterproto.Message):
          is_win: bool = betterproto.bool_field(1)
          changed_exp: "BattleEndChangedPlayerExp" = betterproto.message_field(2)
      
    @dataclass(eq=False, repr=False)
    class BattleEndchangedPlayerExp(betterproto.Message):
          old_exp: int = betterproto.sint32_field(1)

"BattleEndChangedPlayerExp" and "BattleEndchangedPlayerExp" are different
There  something wrong about camel case

**Comment by abn** [comment]
@Gobot1234 The current behaviour leads to errors as the type hint is different to class name, this bricks it. See test case in #353.

**Comment by Miisakiiisakii** [comment]
> 

thanks

**Comment by Gobot1234** [comment]
> @Gobot1234 The current behaviour leads to errors as the type hint is different to class name, this bricks it. See test case in #353. 

Sorry I didn't catch that
