### ISSUE TITLE
support for proto3 `optional` (explicit field presence)

### ISSUE THREAD

**Issue by githorse** [danielgtaylor/python-betterproto#35]
In betterproto it seems like all fields are optional, in that `proto.field = None` is a valid operation. However, there doesn't seem to be any way to indicate a missing field when using the constructor; instead, missing fields get their default values (e.g., 0 for an int).

```
message Pizza {
  string name  = 1;
  int32 radius = 2; 
}

>>> pizza = betterproto.Pizza(name='neapolitan', radius=9)
betterproto.Pizza(name='neapolitan', radius=9)
>>> pizza.radius = None
>>> pizza
betterproto.Pizza(name='neapolitan', radius=None)

>>> pizza = betterproto.Pizza(name='neapolitan')
betterproto.Pizza(name='neapolitan', radius=0)

>>> pizza = betterproto.Pizza(name='neopolitan', radius=None)
*** SyntaxError: invalid syntax
```

If I understand [this announcement](https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md) correctly, the `optional` keyword is now available in proto3 in experimental release 3.12. Is there any plan for the betterproto compiler to take advantage of the new proto3 `optional` keyword to differentiate optional and required fields? It would be great if only explicitly `optional` fields permitted assignment of `None`, whether directly or through the constructor.

**Comment by nat-n** [comment]
Explicitly representing field optionality makes sense. Actually enforcing it at runtime with python dataclasses would be a bit tricky.

**Comment by kalzoo** [comment]
+1 - as a quick(er) fix, even just internally treating the optional field as a `oneof` with only one option would allow `betterproto` to be used with protobuf definitions that can currently be handled by other language generators like `protoc-gen-go` and `prost` (Rust). On-the-wire that should be compatible, IIUC, and then it would just be a matter of improving ergonomics in Python as time allows. 

As it stands, if we select `betterproto` as our Python generator, we have to remove `optional` from all of its source proto definitions, even if all other generators can handle it.

**Comment by davidmankin** [comment]
I just had a PR in my project reverted because it used `optional int32` and a consumer of the proto files uses betterproto.  

I wasn't even aware of betterproto, but it looks better in almost every way — except that it doesn't support the new(ish) `optional` keyword for primitives.  Please consider adding this support.  (I don't need it to enforce that I only put "None" on optional fields; I just need it to be interoperable with the rest of the protobuf ecosystem.   Essentially, what @kalzoo said.)

**Comment by Gobot1234** [comment]
v.2.0.0b4 has just been released and includes support for this.
