### ISSUE TITLE
Proposal for generating docstrings

### ISSUE THREAD

**Issue by 124C41p** [danielgtaylor/python-betterproto#362]
As of version 2.0.0b4, `betterproto` translates Protobuf comments into Python comments. That is, a message
``` proto
message Test {
    // this is foo
    string foo = 1;
    // this is bar
    int32 bar = 2;
}
```

is translated into a dataclass

``` python
@dataclass(eq=False, repr=False)
class Test(betterproto.Message):
    # this is foo
    foo: str = betterproto.string_field(1)
    # this is bar
    bar: int = betterproto.int32_field(2)
```

Unfortunately, these comments are not recognized by some IDEs (I am using VSCode + pylance). Have you thought about translating Protobuf comments into Python docstrings? If you would instead translate `Test` into

``` python
@dataclass(eq=False, repr=False)
class Test(betterproto.Message):
    foo: str = betterproto.string_field(1)
    """this is foo"""
    bar: int = betterproto.int32_field(2)
    """this is bar"""
```
then I would see those comments by hovering over the attributes (`foo`, `bar`) in my IDE without having to look into the actual definition of the class. 

Thank you in advance!

**Comment by Gobot1234** [comment]
This is already implemented in #304 and should be included in 2.0.0b5 (no ETA on when that will be out however sorry).
