### ISSUE TITLE
Repeated empty messages are left out of serialization

### ISSUE THREAD

**Issue by jakkes** [danielgtaylor/python-betterproto#368]
This is a pretty huge deal I have to say, and required me to back to the "official" python compiler (ugh!).

```
message B {
    float x = 1;
}

message A {
    repeated B b = 1;
}
```

If I pass messages `B` into `A`, then any message `B` with `x=0` is ignored in the serialization, effectively dropping data.

**Comment by Gobot1234** [comment]
This is fixed on V.2.0.0bx install it with `pip install betterproto --pre`
