### ISSUE TITLE
Generated parameters

### ISSUE THREAD

**Issue by gnimor** [danielgtaylor/python-betterproto#371]
To be honest I have to say that I am new to python and also grpc.  I have a proto file:

```
service MyService {
  rpc DiscoverDevices (DiscoverDevicesRequest) returns (DiscoverDevicesReply);
}

message DiscoverDevicesRequest {
    int32 identifier = 1;
}

message DiscoverDevicesReply {
  bool successful = 1;
}
```

And the created python function after compilation with betterproto looks like this:

```
async def discover_devices(self, *, identifier: int = 0) -> DiscoverDevicesReply:
    """Start device discovery"""

    request = DiscoverDevicesRequest()
    request.identifier = identifier

    return await self._unary_unary(
        "/XXX.CallService/DiscoverDevices",
        request,
        DiscoverDevicesReply,
    )
```

So when I try a call like this, it fails:

`response = await service.discover_devices(test.DiscoverDevicesRequest(identifier=1))`

but this work:

`response = await service.discover_devices(identifier=1)`

It is clear based on the method definition above. But based on the demos in the documentation of betterproto I thought it would create a function which can be called like

`response = await service.discover_devices(test.DiscoverDevicesRequest(identifier=1))`

Did I miss something during the compilation?

**Comment by Gobot1234** [comment]
This was changed in v2.0.0b4, if you want this, install it using pip install -U betterproto --pre.
