### ISSUE TITLE
installation failed with package version dependency

### ISSUE THREAD

**Issue by wj-Mcat** [danielgtaylor/python-betterproto#373]
## Description

When installing the package with command: 

```shell
pip install betterproto[compiler]>=2.0.0b4
```

it will also install the `Jinja2` package, but it require the verison: jinja2<3.0.0 and >=2.11.2 which will occur the error when generate the code, you can refer to: https://github.com/wechaty/grpc/runs/6096315455?check_suite_focus=true. 

So let' upgrad the version of jinja2 in installation with pip.

**Comment by Gobot1234** [comment]
Already fixed in https://github.com/danielgtaylor/python-betterproto/commit/eeddc844a5bc17c569f1e50f4e812878ac974c34, you'll need to hold tight for the next release (see #350)
