### ISSUE TITLE
Server-Facing Stubs

### ISSUE THREAD

**Issue by jnnks** [danielgtaylor/python-betterproto#391]
The readme mentions that python servers can also be generated. Is that still the case?
The sample instructions in the main readme do not work (EchoBase cannot be found).

**Comment by FHTMitchell** [comment]
The readme is for the beta version 2, you will need to install that if you want server stubs

**Comment by jnnks** [comment]
I see, thanks. That is the branch `release-v2.0.0b1`? EchoBase is still not generated.

`make full-test` works (except for 28 xfailed, 9 xpassed).

`protoc -I .. --plugin=protoc-gen-custom=betterproto/plugin.py --custom_out=output ../echo.proto` was used for the generation. Is that correct?

**Comment by AlexanderZender** [comment]
There seem to be a bug with the 2.0.4b, at least when you install it on a fresh .venv:

Installing straight from the source with: pip install git+https://github.com/danielgtaylor/python-betterproto.git@v2.0.0b4
doesn´t install the compiler to generate the python file and lead to above error message.

You need to install it in the correct order:
1. pip install "betterproto[compiler]"
2. pip install git+https://github.com/danielgtaylor/python-betterproto.git@v2.0.0b4
3. pip install grpcio-tools
4. compile
5. compiles __init__.py

If you install the 2.0.0b4 version before the compiler, the compiler won't install and compiling will produce said error:
1. pip install git+https://github.com/danielgtaylor/python-betterproto.git@v2.0.0b4
2. pip install "betterproto[compiler]"
3. pip install grpcio-tools
4. compile
6. error

best regards

**Comment by Gobot1234** [comment]
The recommended way to install the compiler dependencies and b4 is with `pip install -U "betterproto[compiler]" --pre`
