### ISSUE TITLE
Can't run in virtualenv?

### ISSUE THREAD

**Issue by 0x0ece** [danielgtaylor/python-betterproto#393]
Repro:
```
$ python3 -mvenv venv
$ source venv/bin/activate
$ pip install --pre betterproto "betterproto[compiler]"
$ protoc-gen-python_betterproto
Unable to import `markupsafe` from betterproto plugin! Please ensure that you've installed betterproto as `pip install "betterproto[compiler]"` so that compiler dependencies are included.
```

Needless to say, `markupsafe` is installed in the virtualenv.
I tried both on a linux box (py 3.7.3) and on a Mac (py 3.8.9), with different combinations of protoc.

Unfortunately I strictly need to use a form of virtualenv as I can't be root on these machines. Any alternative to virtualenv would work on my side, I'm just trying to have the compiler to work. Thank you!

Edit: tested also on py 3.10.2, 3.10.5. For some reason, on 3.9.2 it worked (but then I got other issues compiling my protobuf, so not entirely sure).

**Comment by wimglenn** [comment]
https://github.com/pallets/jinja/issues/1585
