### ISSUE TITLE
Considerably Worse Performance on 2.0.0b4 vs Regular Protoc?

### ISSUE THREAD

**Issue by steve-gray** [danielgtaylor/python-betterproto#398]
Given a moderately complex GRPC object structure (one that in go can be processed about a quarter million times a second), I was finding the Protoc Python generator to be quite slow due to what seems to be almost exclusively reflection based encoding. For example, executing a model taking 0.6 seconds, but encoding it to GRPC on the wire taking 1.1 and change.

Screenshot from Bloom, showing our code running and the timing being 1.7s

<img width="772" alt="image" src="https://user-images.githubusercontent.com/14563775/176861217-e0b7face-fd9f-467b-9b0a-26566358b97d.png">

So, yeah. Wasn't stoked. Rolled onto this project - seemed to have a lot of issues gettting the published version for the server code to work, so gave up there and decided to try the latest `2.0.0b4`  only to find the performance was far worse:

- I'm using GRPCLib / Jinja2 latests to avoid issues with code either not generating or objects being missing.
- AIO everywhere in the stack.
- Running repeated tests to pay-down any one-off per-request overhead.

Regardless, I've got this taking nearly 8 seconds to run for the same workload:

<img width="764" alt="image" src="https://user-images.githubusercontent.com/14563775/176860594-226768f6-13b2-409e-a6aa-0ee4ae8eb7b9.png">

Device is an Apple MacBook Pro 32gb, i9 six-core/12 thread machine ticking over on idle when not running this code.

Am I missing a trick, or is the conscious trade-off for this project more idiomatic python (I support the goal, the official Python generation looks like a C++ macro escaped and became sentient), but at the cost of performance?

**Comment by Gobot1234** [comment]
Pretty much, see my comments in #314

**Comment by steve-gray** [comment]
Ah damn. Somehow I missed that one during all my travels trying to get this up and working. Thanks for the prompt response @Gobot1234. Sorry for not checking the threads more thoroughly.  

In terms of performance, is there anything akin to the PlanetScale/VTProto for Golang where all the code is unrolled for performance? Failing that, I might start looking at at flatbuf/capnproto type solutions.

**Comment by Gobot1234** [comment]
I personally haven't tested it but https://proto-plus-python.readthedocs.io/en/latest/index.html is something that might be worth looking into, it won't type check as nicely as betterproto but it's probably faster as it still uses the underlying c++ code.

**Comment by steve-gray** [comment]
Thanks. I'll have a sniff around on that one.
