### ISSUE TITLE
Generated python files do not contain imports when using import in .proto files

### ISSUE THREAD

**Issue by juergstaub** [danielgtaylor/python-betterproto#408]
I have a structure where I have some base .proto messages defined that are used in other messages.  Those messages import the respective base message .proto files. 

The betterproto compiler creates all .py files but does not import the respective python modules in modules that have dependencies.

**Comment by Gobot1234** [comment]
What version are you using?

**Comment by juergstaub** [comment]
1.2.5

**Comment by juergstaub** [comment]
Did so, and now I have version 2.0.0b5 installed, but the protoc command fails now with --python_betterproto_out: protoc-gen-python_betterproto: Plugin failed with status code 1.

**Comment by Gobot1234** [comment]
You probably don't have the compiler imports `pip install "betterproto[compiler]" --pre`

**Comment by juergstaub** [comment]
Yes, you are right, I installed the compiler (2.0.0b5), but now it just generates a single file (__init__.py) containing all classes

**Comment by Gobot1234** [comment]
That's a known issue see https://github.com/danielgtaylor/python-betterproto/issues/357

**Comment by juergstaub** [comment]
Ok, thanks for the fast responses, very much appreciated.
