### ISSUE TITLE
protoc hangs with betterproto plugin

### ISSUE THREAD

**Issue by jdvor** [danielgtaylor/python-betterproto#411]
Using betterproto plugin, protoc compiler hangs when protobuf definition files are containing `import` directive.
Hangs = the console command does not terminate and the SIGTERM signal (Ctrl + C) must be used to force the exit.
Compilation without the plugin terminates correctly as expected in the same situation.

[Here](https://github.com/jdvor/betterproto-hangs) is the simplest possible repo with reproduction steps.

OS: Windows 10 x64
Python: 3.9.13
betterproto: 1.2.5
protoc-wheel-0: 21.1
Tried several methods of protoc invocation with the same result: cmd.exe, powershell, subprocess.call

**Comment by Gobot1234** [comment]
I can't reproduce this on macOS 12.4 
```sh
python3.9 -m pipenv run protoc_bp
Writing __init__.py
Writing another.py
Writing simple.py
```

**Comment by jdvor** [comment]
I've tried it with pre-release as well and it behaves the same. It's definitely some interplay between plugin and the protoc **from the wheel** (3.20.1). Have you used the repo with the reproduction? Because I can't see how you would have protoc version 3.21.4 and not 3.20.1

I'm thinking about creating a replication including Dockerfile, so the effects of anyone's local environment are out of the picture.

**Comment by Gobot1234** [comment]
I did use the repo, I didn't realise that it was installing another protoc wheel, maybe that's the issue then.

**Comment by jdvor** [comment]
Yes, `pipenv install` creates its own virtual environment to which it brings protoc executable through dependency protoc-wheel-0.

Anyways, I've tried to reproduce it using Docker image based on python:3.9.13-bullseye-slim and **was not able to reproduce it**. So, I think you can close the issue. The behavior heavily depends on environment and as such nothing can be really done about it with **reasonable** effort.

If it will be of any use to you, than you can use the "Steps to reproduce 2 (Docker image)" from [original repo](https://github.com/jdvor/betterproto-hangs) to test similar cases in truly isolated environment.
