### ISSUE TITLE
Type checking async iterator methods with mypy not working correctly

### ISSUE THREAD

**Issue by anriha** [danielgtaylor/python-betterproto#412]
When you try to type check method that returns stream mypy will complain about incompatible type with supertype. This is due to the fact that for mypy to consider something AsyncIterator it needs to have yield somewhere in it's implementation. 
```python
async def get_trucks(self, order_id: str) -> AsyncIterator["OrderTruckResponse"]:
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)
```
So something like this is considered Coroutine[Any, Any, AsyncIterator]], while
```python
async def get_trucks(self, order_id: str) -> AsyncIterator["OrderTruckResponse"]:
        if False:
                yield OrderTruckRespnse()
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)
```
would be AsyncIterator["OrderTruckResponse"].

For more info check mypy issue.
https://github.com/python/mypy/issues/12662

**Comment by Gobot1234** [comment]
I think the easiest way to do this is just
```py
def fn():
    raise Error
    yield Type()
```
And that's a simple fix in the compiler and the jninja template

**Comment by anriha** [comment]
Yes that should definitely work and you are right that is better than my solution. If this solution is ok I don't mind opening PR with this.

**Comment by Gobot1234** [comment]
That'd be great thank you!
