### ISSUE TITLE
Separating compiler dependencies from runtime dependencies

### ISSUE THREAD

**Issue by kyle-query** [danielgtaylor/python-betterproto#433]
Could these dependencies be removed from `tool.poetry.dependencies` in pyproject.toml?

* black
* isort
* jinja2

They are used only when running the compiler, and they are listed in `tool.poetry.extras`; so running `pip install betterproto[compiler]` would still install them. Maybe you can declare version constraints in the `extras` if needed.

**Comment by Gobot1234** [comment]
They are already optional and so aren't installed by default, I'm not really sure what you want to be done here

**Comment by kyle-query** [comment]
Thanks, you're right.
