### ISSUE TITLE
module 'betterproto' has no attribute 'Field'

### ISSUE THREAD

**Issue by NickTheHuy** [danielgtaylor/python-betterproto#454]
Traceback (most recent call last):
  File "c:\Users\nikur\meh\client.py", line 4, in <module>
    class Person(betterproto.Message):
  File "c:\Users\nikur\meh\client.py", line 5, in Person
    name = betterproto.Field(betterproto.string, 1)
           ^^^^^^^^^^^^^^^^^
AttributeError: module 'betterproto' has no attribute 'Field'

**Comment by Gobot1234** [comment]
This isn't code generated by the compiler included, that should look like string_field. If you want code to run please use the generator
