### ISSUE TITLE
JIT compilation

### ISSUE THREAD

**Issue by beasteers** [danielgtaylor/python-betterproto#455]
One thing that has always confused me is why gRPC requires a compilation stage and why it doesn't just have a runtime API. I understand that it's probably to reduce runtime dependencies and also to make the upstream polyglot development easier, but it always seemed like an unnecessary awkward step.

Ideally, you'd just be able to import class decorators and have that implicitly do the spec generation (and caching perhaps).

It's a turn-off for me and I've never used gRPC for this reason, so I'm just kind of curious why things are the way they are.

**Comment by Gobot1234** [comment]
Hi this isn't really the place to ask questions about gRPC's design choices, these types of questions are more suited for stackoverflow or our [slack group](https://join.slack.com/t/betterproto/shared_invite/zt-f0n0uolx-iN8gBNrkPxtKHTLpG3o1OQ)

Thank you for your understanding
