### ISSUE TITLE
None and False not working

### ISSUE THREAD

**Issue by yingshaoxo** [danielgtaylor/python-betterproto#458]
Here is the protobuff code:
```proto
message Friend {
    string email = 1;
    string name = 2;
    string nickname = 3;
    bool got_blocked = 4;
    bool super_like = 5;
}
```

If I set `got_blocked` to `null`, the `received dict` will become `False`.

If I set `got_blocked` to `False`, the generated dict by `Friend().to_dict()` won't include `got_blocked`.

___

my package version: `betterproto[compiler]==2.0.0b5`

**Comment by cetanu** [comment]
This is consistent with protobuf behavior where a bool has a default value of `false`

So if you specify `none`, i.e. no value, it will use the default instead.

The `to_dict` and `to_json` methods will also not include default values by default. You can force it to include them with `include_default_values=True`
