### ISSUE TITLE
Servicer code not generated

### ISSUE THREAD

**Issue by NiklasRosenstein** [danielgtaylor/python-betterproto#464]
Hi 👋 This is the first time I'm trying out betterproto! The README states that servicer base classes are also rendered into the generated code (i.e. `EchoBase`). But that's not the case for me, I'm not only getting `Stubs` but not `Base` classes for the `service {}` blocks in my Protobuf files.

I've got `betterproto 1.2.5` installed.

Am I missing an option to generate this code?

Thank you

**Comment by NiklasRosenstein** [comment]
Ah, I need to use `^2.0.0b5`.

**Comment by mxrch** [comment]
You saved me thousands of hours of debugging, thank you @NiklasRosenstein !
The examples in the readme should specify that it uses features from the pre version.
