### ISSUE TITLE
Unknown flag: `--custom_opt`

### ISSUE THREAD

**Issue by hugokitano** [danielgtaylor/python-betterproto#465]
Simply following the main README here:

```
protoc -I . --python_betterproto_out=lib --custom_opt=pydantic_dataclasses analytics_event.proto
Unknown flag: --custom_opt
```
What's going on here? Thanks

**Comment by MarekPikula** [comment]
It should be in fact `--python_betterproto_opt=pydantic_dataclasses`. Someone copied and pasted from tests with wrong prefix. Took me a while to figure out how the plugin system works for protoc. Also, mind that this feature is not yet released, so you need to install from master branch to benefit from this feature.

**Comment by MarekPikula** [comment]
Ah, sorry, I didn't check and it seems that there are some pre-releases for 2.0: https://pypi.org/project/betterproto/#history
