### ISSUE TITLE
Non-empty fields with empty messages should be encoded

### ISSUE THREAD

**Issue by GrownNed** [danielgtaylor/python-betterproto#466]
betterproto skips fields whose values are empty messages. This is different from the behavior of the official protobuf package.

```proto
syntax = "proto3";

package test;

enum PhoneType {
    MOBILE = 0;
    HOME = 1;
    WORK = 2;
}

message PhoneNumber {
    string number = 1;
    PhoneType type = 2;
}

message Person {
    PhoneNumber phone = 1;
}
```

```py
import test_pb2
import test_bp


person_pb2 = test_pb2.Person()
person_pb2.phone.CopyFrom(test_pb2.PhoneNumber())
print(f"{person_pb2.SerializeToString().hex()=}")


person_bp = test_bp.Person()
person_bp.phone = test_bp.PhoneNumber()
print(f"{bytes(person_bp).hex()=}")
```

```
person_pb2.SerializeToString().hex()='0a00'
bytes(person_bp).hex()=''
```

**Comment by Gobot1234** [comment]
What version are you on? Im fairly confident this is fixed in v2.0.0b5

**Comment by GrownNed** [comment]
2.0.0b5

**Comment by Algoinde** [comment]
I'm affected by this as well, and can confirm this is the behavior on v2.0.0b5. For compatibility reasons with different wacko protobuf implementations, I think this could be a flag on whether to include the empty fields?

**Comment by Gobot1234** [comment]
> I'm affected by this as well, and can confirm this is the behavior on v2.0.0b5. For compatibility reasons with different wacko protobuf implementations, I think this could be a flag on whether to include the empty fields?

There's no good way to pass arguments to bytes(message) so I think it's best we stick to conform with google's implementation and you should file issues with other libraries

**Comment by Gobot1234** [comment]
This is now fixed in b6
