### ISSUE TITLE
Some message structures are not serialised properly

### ISSUE THREAD

**Issue by olijeffers0n** [danielgtaylor/python-betterproto#479]
Hi, the project I am working on makes use of "AppEmpty" messages which signify that a certain element should be sent back. The proto looks something like this:

```proto
message Request {
		required uint32 seq = 1;
		required uint64 playerId = 2;
		required int32 playerToken = 3;
		
		optional AppEmpty getInfo = 8;
		optional AppEmpty getTime = 9;
}

message AppEmpty {	
}
```

Where I am then using betterproto to be able to do this:
```py
request = AppRequest()
request.seq = 1
request.player_id = 5
request.player_token = 10
request.get_info = AppEmpty()
print(betterproto.serialized_on_wire(request.get_info)) # False
```
However, the `get_info` request is not then serialised. I may be doing something wrong, however currently I am just setting the internal serialisation state with:
```py
app_request.get_info._serialized_on_wire = True
```

Am I doing something wrong or is there a problem?

**Comment by Gobot1234** [comment]
What version of the project are you using? If you aren't already on V2 please can you try using that (`pip install betterproto --pre`)

**Comment by olijeffers0n** [comment]
I have just tried this, without manually setting the `_serialized_on_wire` attribute it does not work on version `2.0.0b5`

**Comment by olijeffers0n** [comment]
This can be "fixed" by adding some logic to the `__setattr__` of the `Message` class. I have opened a PR that links to this

**Comment by Gobot1234** [comment]
Sorry closed this too early
