### ISSUE TITLE
Switch pipenv for poetry

### ISSUE THREAD

**Issue by nat-n** [danielgtaylor/python-betterproto#48]
[Poetry](https://python-poetry.org/) is a popular alternative to pipenv that also abstracts over dependency and build management using pyproject.toml, but arguably does a better job, particularly in terms of simplifying the process.

I've seen several cases (in addition to my own experience) of contributors on this repo having some difficulty with pipenv, and I think switching to poetry would make the process smoother thus lowering this barrier a little.

5 minutes googling presents a fairly one sides picture of the relative benefits of poetry vs pipenv: 

- https://python.libhunt.com/compare-poetry-vs-pipenv 
- https://news.ycombinator.com/item?id=21510597
- https://johnfraney.ca/posts/2019/11/19/pipenv-poetry-benchmarks-ergonomics-2/
- https://frostming.com/2019/01-04/pipenv-poetry
- https://www.reddit.com/r/Python/comments/aox5ah/moving_away_from_pipenv/

I'd be happy to work on migrating the project to poetry if there are no objections. @danielgtaylor

**Comment by boukeversteegh** [comment]
Man, I've wasted more than a day on getting my environment to work with pipenv! I'd be happy if that could be made easier in any way.

I don't know poetry though.. do you think it's mature enough, and have you seen it being used it in any mildly serious project?

**Comment by boukeversteegh** [comment]
Merged by #75
