### ISSUE TITLE
v2+ on pypi does not create code files

### ISSUE THREAD

**Issue by morganics** [danielgtaylor/python-betterproto#480]
Hi, I'm on the latest full release which generates files very well, in the appropriate places, but does not support optionals. I then tried out the v2.* library but I've found that just creates folders for each proto specified with an __init__.py, but no code files. Maybe I'm using the wrong command line - has it changed from v1.*? Here is the command I'm using (on Windows):

```python -m grpc_tools.protoc -I c:/proto_path --python_betterproto_out=../libs c:/proto_path/my_proto_file.proto```

With the above on v1.2.5 I get the files in `package_name/my_proto_file.py`, and 2 dependencies, but in v2.* I get `package_name/my_proto_file/__init__.py` and 2 further sub folders for the dependencies. Any help would be appreciated.

**Comment by Gobot1234** [comment]
This is a known issue see #357
