### ISSUE TITLE
Generate `py.typed` as a part of generated library

### ISSUE THREAD

**Issue by gudjonragnar** [danielgtaylor/python-betterproto#483]
I think it might be valuable to allow for `py.typed` to be generated as a part of the generator output. This would be useful for cases where the generated code is bundled into a library and consumed by other projects.

**Comment by Gobot1234** [comment]
This shouldn't be required for bundled generated code
> This marker applies recursively: if a top-level package includes it, all its sub-packages MUST support type checking as well - https://peps.python.org/pep-0561/#packaging-type-information 
so unless for some reason people are including these as top level packages I don't think this is useful
