### ISSUE TITLE
Would it be possible to release a new version?

### ISSUE THREAD

**Issue by ashwin153** [danielgtaylor/python-betterproto#493]
- I'd like to use the pydantic_dataclasses feature, but it doesn't appear to have been released.
- Would it be possible to cut a 2.0.0 release?

**Comment by Gobot1234** [comment]
Hi, as I've said somewhere else I can't cut a release all by myself so there's nothing I can do here right now. You'll need to get another maintainer to help or open a PR for me to review to do this.
