### ISSUE TITLE
Reflection doesn't work with grpclib

### ISSUE THREAD

**Issue by nimish** [danielgtaylor/python-betterproto#5]
Steps to repro: generate any proto, create a grpclib server, then add on reflection. Lastly, try asking for the reflection info using grpcurl: it'll fail.

**Comment by danielgtaylor** [comment]
I'm not super familiar with the grpclib reflection generation code, so will need some time to dig into this. Treating it as a feature request for now and will gladly accept help if anybody is willing. Thanks!

**Comment by nimish** [comment]
Makes sense. It does seem that grpclib tightly couples to the standard protobuf DESCRIPTOR-style to generate the reflection info.

**Comment by lambdalisue** [comment]
So this issue has closed but betterproto does NOT support reflection yet, right?

**Comment by BananaLoaf** [comment]
@lambdalisue I found a way in #443

**Comment by BananaLoaf** [comment]
I forgot about OP @nimish - #443

**Comment by BananaLoaf** [comment]
Forgot about OP @nimish and dev @vrazdalovschi - #443

**Comment by BananaLoaf** [comment]
Forgot about OP @nimish and dev @danielgtaylor - #443
