### ISSUE TITLE
Add license file to GitHub repository

### ISSUE THREAD

**Issue by mfridman** [danielgtaylor/python-betterproto#501]
If possible, it'd be nice to have a license file committed to the repository. That way projects that rely on the source can link to a license file without going to [pypi](https://pypi.org/project/betterproto/) or the mention in the readme.

**Comment by Sriansh-raj** [comment]
assign me 😃

**Comment by Sriansh-raj** [comment]
> 

I have added a `LICENSE.md` with author name `Daniel G. Taylor`

**Comment by Gobot1234** [comment]
Completed in #502
