### ISSUE TITLE
Message to_dict for TYPE_ENUM  IndexError: list index out of range

### ISSUE THREAD

**Issue by weixiaovision** [danielgtaylor/python-betterproto#503]
```py
class ActivityType(betterproto.Enum):


    ActivityType_None = 0
    ActivityType_MulanTrial = 62005

@dataclass
class ActivityCancelNewTagC2S(betterproto.Message):

    type: "ActivityType" = betterproto.enum_field(1)

msgC2S = ActivityCancelNewTagC2S()
msgC2S.type = 62005
msgC2S.to_dict()
```

**Comment by Gobot1234** [comment]
This code runs fine for me, what version are you on?

**Comment by Gobot1234** [comment]
@lis-yana can you update to the latest pre release from pypi and see if the issue persists

**Comment by lis-yana** [comment]
> @lis-yana can you update to the latest pre release from pypi and see if the issue persists

After updating to latest beta version the issue is no longer reproducible, great!
