### ISSUE TITLE
Automate releases with Semantic Releases, towncrier, or similar

### ISSUE THREAD

**Issue by MicaelJarniac** [danielgtaylor/python-betterproto#504]
- [Python Semantic Release](https://github.com/python-semantic-release/python-semantic-release)
  - [Semantic Release](https://github.com/semantic-release/semantic-release)
- [Semantic Versioning](https://semver.org)
- [Conventional Commits](https://conventionalcommits.org)
- [towncrier](https://github.com/twisted/towncrier)

These tools might help with automating the release process, and result in easier and quicker releases.

I personally write my commit messages following Conventional Commits, and use Python Semantic Release to automate the process of generating the new Semantic Version of the project, the changelog, and actually push it to PyPI and such.

I heard good things about towncrier, but have never personally used it.

If there's interest, I could help set these tools up and write an explanation of how to best work with them.

**Comment by Gobot1234** [comment]
Work towards this was already started in #286

**Comment by MicaelJarniac** [comment]
I should have searched for it before opening an issue, my bad.
But at least I also mentioned some other tools that could be considered.
