### ISSUE TITLE
Library seems to not work at all with latest protobuf version

### ISSUE THREAD

**Issue by SamuelYvon** [danielgtaylor/python-betterproto#506]
Running Linux 86-64, protobuf 23.3. Installed by manual unzipping of the latest release if that matters.

Using the default example:

```protobuf
syntax = "proto3";

package hello;

// Greeting represents a message you can tell a user.
message Greeting {
      string message = 1;
}
```

And then running the example compile command:

```shell
protoc -I . --python_betterproto_out=lib example.proto
```

Prints out the very opaque `--python_betterproto_out: protoc-gen-python_betterproto: Plugin failed with status code 1.` (I know the error comes from protoc). 

I'm trying to run previously working protoc compilation to pydantic; but even this basic example does not work. I'm investigating on the side; it is possible I am missing a system dependency?

Running `betterproto             2.0.0b5`

**Comment by Gobot1234** [comment]
Have you installed betterproto with the `[compiler]` option?

**Comment by SamuelYvon** [comment]
Darnit. I installed from poetry with `extras=["compile"]` and not `compiler`. Nice catch. Is there a way to make this more explicit?

**Comment by Gobot1234** [comment]
Honestly not sure but I sure wish there was :)
