### ISSUE TITLE
Unconventional `__eq__` method behavior

### ISSUE THREAD

**Issue by coffee-lord** [danielgtaylor/python-betterproto#512]
Possibly due to

https://github.com/danielgtaylor/python-betterproto/blob/6faac1d1ca4b979704c145d968dfed8e38fe159c/src/betterproto/__init__.py#L654

returning `False` instead of `NotImplemented` (see Python docs [here](https://docs.python.org/3/reference/datamodel.html#object.__eq__)), the following snippet doesn't work as expected:

```python
from dataclasses import dataclass
from unittest.mock import ANY
import betterproto

@dataclass(eq=False, repr=False)
class Foo(betterproto.Message):
    pass

assert Foo() == ANY  # Expected to pass but raises AssertionError
```

This is a minimal reproducible example. The actual use case is related to how [syrupy](https://github.com/tophat/syrupy) and pytest check assertions. The following test crashes with an enigmatic error `KeyError: -1` which is indirectly caused by betterproto's `__eq__` method, which doesn't delegate comparison to the right hand side argument in case of a type mismatch. (Which is what returning `NotImplemented` is for)

```python
# pytest 7.4.0
# syrupy 4.0.8

from dataclasses import dataclass
import betterproto

@dataclass(eq=False, repr=False)
class Foo(betterproto.Message):
    pass

def test_foo(snapshot):
    foo = Foo()
    assert foo == snapshot
```

**Comment by Gobot1234** [comment]
Would you be willing to open a PR to fix this?
