### ISSUE TITLE
Error when printing a message with oneof fields

### ISSUE THREAD

**Issue by 124C41p** [danielgtaylor/python-betterproto#521]
On latest master branch, there seems to be something wrong with messages containing oneof fields.

```python3
from dataclasses import dataclass
import betterproto

@dataclass
class Foo(betterproto.Message):
    a: str = betterproto.string_field(1, group="g")
    b: int = betterproto.int32_field(2, group="g")

foo = Foo(a = "test")
print(foo)
```

This snipped raises the following: `AttributeError: 'g' is set to 'a', not 'b'`

**Comment by Gobot1234** [comment]
What happens if you pass repr = False to the dataclass

**Comment by 124C41p** [comment]
With repr=False it works just fine. So setting `repr=False` is mandatory when creating messages?

**Comment by Gobot1234** [comment]
Yes
