### ISSUE TITLE
pydantic v2 support

### ISSUE THREAD

**Issue by DeoLeung** [danielgtaylor/python-betterproto#530]
Hi,

Thanks for the great job.
I'm just wondering whether pydantic v2 support is on the way, seems using `root_validator` is raising error in v2.

like `langchain` use a [submodule import](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/pydantic_v1/__init__.py) .

**Comment by bigluck** [comment]
Hi all, is there any update on this? I would love to use betterproto, but I can not switch back to pydantic v1.

Thanks

**Comment by jafaircl** [comment]
Maybe I'm wrong but I don't think limiting pydantic to an outdated version is an ideal solution to this issue. Is this the only problem with it? The error message I get indicates that you just need to specify `skip_on_failure=True` in the `root_validator` decorator (which should be replaced with `model_validator` either way). Would you accept a PR that makes that change?
