### ISSUE TITLE
Dataclasses generated despite `--python_betterproto_opt=pydantic_dataclasses`

### ISSUE THREAD

**Issue by raj-open** [danielgtaylor/python-betterproto#533]
Hi, I have the following setup
```text
. # some directory, bash commands invoked from here.
|
|____ gen/
|    |____ ... # will be filled
|
|____ schemas/
|    |____ example.proto
|    |____ ...
|
| ...
```
and tried running
```bash
mkdir lib
protoc -I . --python_betterproto_opt=pydantic_dataclasses --python_betterproto_out=lib schemas/example.proto
```
where `schemas/example.proto` is
```proto
syntax = "proto3";

package hello;

// Greeting represents a message you can tell a user.
message Greeting {
  string message = 1;
}
``` 
This results in 
```py
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: schemas/example.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Greeting(betterproto.Message):
    """Greeting represents a message you can tell a user."""

    message: str = betterproto.string_field(1)
```
instead of a Pydantic class.

**Q1.** What am I doing wrong? Is there something I need to do to get protoc to recognise the `--python_betterproto_opt` option?

Also, I prefer to use the [Buf cli](https://buf.build/product/cli) (i.e. with config files), as this is much cleaner than working directly with `protoc`, `grpc_tools.protoc`, etc. Setting up **buf.gen.yaml** as
```yaml
version: v1
plugins:
  - plugin: buf.build/community/danielgtaylor-betterproto:v1.2.5
    out: generated
```
and running
```bash
buf generate --include-imports
```
generates your dataclasses nicely.

**Q2.** Would it be possible to add this to your documentation?

**Q3.** Is there a way to add the `pydantic_dataclasses` option to these config files?

(_I should post this perhaps separately_) **QZ.** Will there be support for validation? This would be fantastic, as the `pydantic` data classes have excellent support for validation. On the protocol buffers side, there is a 'standard' way of implementing validation (see <https://github.com/bufbuild/protovalidate> and <https://buf.build/envoyproxy/protoc-gen-validate>). However, 1) I have not seen a example for python that works out-of-the-box, and 2) the developers behind this seem to be more focussed on go, and provide very rudimentary support for python, i.e. I suspect they don't have in mind to provide pydantic-support.

Thanks in advance!

**Comment by Gobot1234** [comment]
V1.2.5 doesn't have support for pydantic you need to use the latest version from github. I'm not familiar with buf so I can't really answer the rest of your questions but as I understand we can't put the package on buf whilst the project is still in alpha.

**Comment by Gobot1234** [comment]
There's a chance we could get validation working using a similar sort of concept to bufs, but I don't have the drive to implement it myself.
