### ISSUE TITLE
Strip enum prefixes during compilation

### ISSUE THREAD

**Issue by terax6669** [danielgtaylor/python-betterproto#539]
### Summary

It's a common practice to add prefixes to avoid naming collisions, but betterproto does not handle that.

### What is the feature request for?

The core library

### The Problem

The betterproto compiler doesn't strip enum prefixes.

### The Ideal Solution

```protobuf
enum OptionType {
	OPTION_TYPE_NONE = 0;
}
```
should become
```python
class OptionType(betterproto.Enum):
    NONE = 0
```

### The Current Solution

The only solution is editing the generated file every time. Stripping the prefixes in source is not an option, it would not compile due to collisions.

**Comment by Gobot1234** [comment]
Duplicate of https://github.com/danielgtaylor/python-betterproto/issues/174
