### ISSUE TITLE
Warning for optional fields

### ISSUE THREAD

**Issue by gnimor** [danielgtaylor/python-betterproto#564]
### Summary

If proto file contains optional fields a warning will be stated

### Reproduction Steps

When compiling a proto file with optional fields a warning will be reported:

XXX.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-python_betterproto hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.

### Expected Results

Compile without warning

### Actual Results

Warning will be reported

### System Information

Python 3.12.2

Name: betterproto
Version: 1.2.5
Summary: A better Protobuf / gRPC generator & library
Home-page: http://github.com/danielgtaylor/python-betterproto
Author: Daniel G. Taylor
Author-email: danielgtaylor@gmail.com
License: MIT
Location: D:\Code\Kaishin\TokuPic\TokuPic.Clients\Python\venv\Lib\site-packages
Requires: grpclib, stringcase
Required-by:

### Checklist

- [X] I have searched the issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have verified this issue occurs on the latest prelease of betterproto which can be installed using `pip install -U --pre betterproto`, if possible.

**Comment by Gobot1234** [comment]
Update to V2. That has support for optionals.
