### ISSUE TITLE
Optional fields in proto3

### ISSUE THREAD

**Issue by dpkristensen** [danielgtaylor/python-betterproto#574]
### Summary

Unsupported optional fields in proto3

### Reproduction Steps

Run the generator on a .proto file using proto3 and an optional field.

### Expected Results

Proto file is generated

### Actual Results

Message "code generator protoc-gen-python_betterproto hasn't been updated to support optional fields in proto3" is displayed.

### System Information

`libprotoc 26.0
Python 3.11.7
Name: betterproto
Version: 1.2.5
Summary: A better Protobuf / gRPC generator & library
Home-page: http://github.com/danielgtaylor/python-betterproto
Author: Daniel G. Taylor
Author-email: danielgtaylor@gmail.com
License: MIT
Location: C:\Python311\Lib\site-packages
Requires: grpclib, stringcase
Required-by:`

### Checklist

- [X] I have searched the issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have verified this issue occurs on the latest prelease of betterproto which can be installed using `pip install -U --pre betterproto`, if possible.

**Comment by Gobot1234** [comment]
This is already supported on main

**Comment by dpkristensen** [comment]
@Gobot1234 When will the update be published?  Last update on pypi was 4 years ago.

**Comment by Gobot1234** [comment]
> I have verified this issue occurs on the latest prelease of betterproto which can be installed using `pip install -U --pre betterproto`, if possible.

**Comment by dpkristensen** [comment]
Sorry I misread that text.  But my question is about when a new release will occur; pypi shows the CI status is "failing" and I would like not to add a dependency to something which may break in the future.

**Comment by Gobot1234** [comment]
There is no current release date for a full release of V2. The CI failing isn't for V2 I wouldn't worry about it

**Comment by shayneoneill** [comment]
Was there any update on this?

**Comment by dkbarn** [comment]
Development focus seems to have shifted to the fork at https://github.com/betterproto/python-betterproto2/ which is still unreleased.

A message on Discord from one of the developers in May 2025 said:
> There are still a few problems that I need to address before doing a stable release since I want to avoid breaking changes after that, I think it will probably take a few weeks / months more
