### ISSUE TITLE
cannot generated pydantic classes

### ISSUE THREAD

**Issue by leon1995** [danielgtaylor/python-betterproto#585]
### Summary

The option to generate pydantic dataclasses seems to be ignored

### Reproduction Steps

I followed the tutorial and executed `path\to\protoc.exe -I . --python_betterproto_opt=pydantic_dataclasses --python_betterproto_out=lib example.proto`

### Expected Results

make use of pydantic classes

### Actual Results

python builtin `dataclasses` are used
```python
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: example.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Greeting(betterproto.Message):
    """Greeting represents a message you can tell a user."""

    message: str = betterproto.string_field(1)

```

### System Information

protoc `27.2` `win64`
`Python 3.12.0`
```
pip show betterproto
Name: betterproto
Version: 1.2.5
Summary: A better Protobuf / gRPC generator & library
Home-page: http://github.com/danielgtaylor/python-betterproto
Author: Daniel G. Taylor
Author-email: danielgtaylor@gmail.com
License: MIT
Location: C:\Users\budnickl\Downloads\py-proto-converter-test\venv\Lib\site-packages
Requires: grpclib, stringcase
Required-by:
```

### Checklist

- [X] I have searched the issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have verified this issue occurs on the latest prelease of betterproto which can be installed using `pip install -U --pre betterproto`, if possible.

**Comment by Gobot1234** [comment]
Update to 2.0.0b6 please. pip install python-betterproto --pre

**Comment by leon1995** [comment]
I did but now I get the error `--python_betterproto_out: protoc-gen-python_betterproto: Plugin failed with status code 1`

**Comment by Gobot1234** [comment]
You need the compiler extras
