### ISSUE TITLE
Is proto2 syntax supported?

### ISSUE THREAD

**Issue by thisch** [danielgtaylor/python-betterproto#6]
The example in the readme uses proto3 syntax. Is proto2 syntax also supported? Please mention this in the readme. Thx

**Comment by danielgtaylor** [comment]
@thisch no, only proto3 is supported. I don't plan to support proto2 features but I'll try to make that more clear in the README.

**Comment by thisch** [comment]
Good to know. Yesterday I tested python-betterproto with a proto2 proto file and the protoc plugin seemed to handle this file.
