### ISSUE TITLE
Mypy sees enum members as integer

### ISSUE THREAD

**Issue by phooijenga** [danielgtaylor/python-betterproto#600]
### Summary

As of 2.0.0b7, mypy sees enum members as integers

### Reproduction Steps

```python
import betterproto


class Event(betterproto.Enum):
    START = 0
    STOP = 1


e: Event = Event.START
```

### Expected Results

I expect the code to type-check without issues, as it does with 2.0.0b6.

### Actual Results

```
test-enum.py:9: error: Incompatible types in assignment (expression has type "int", variable has type "Event")  [assignment]
```

### System Information

betterproto 2.0.0b7
mypy 1.11.1

### Checklist

- [X] I have searched the issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have verified this issue occurs on the latest prelease of betterproto which can be installed using `pip install -U --pre betterproto`, if possible.

**Comment by Gobot1234** [comment]
Mypy isn't interpreting the bases list correctly. This isn't something we can fix (I've tried)
