### ISSUE TITLE
Enum 0 should exits in result of `Message.to_dict` even `include_default_values=False`

### ISSUE THREAD

**Issue by RF-Tar-Railt** [danielgtaylor/python-betterproto#607]
### Summary

Change the serialize behavior for enum 0

### What is the feature request for?

The core library

### The Problem

To show the problem, here is a simple example. Compile the following proto messages:

```protobuf
enum Role {
  FOO = 0;
  BAR = 1;
  BAZ = 2;
  QUX = 3;
}

message Main {
    Role role = 1; 
}
```

when called `to_dict` method of Main's instance like `Main(role=Role.FOO)`, the result is `{}` instead of `{"role": "FOO"}` 

### The Ideal Solution

In source code of `to_dict`, Enum handler is after step:

```python
elif (
    value != self._get_field_default(field_name)
    or include_default_values
    or self._include_default_value_for_oneof(
        field_name=field_name, meta=meta
    )
):
```

But unfortunately, default value of Enum is 0.

I think the solution is to extract Enum handler to an outer step.

### The Current Solution

The result of `Main(role=Role.FOO).to_dict(include_default_values=True)` is `{"role": "FOO"}` as expected.

**Comment by Gobot1234** [comment]
I don't think this is a bug https://protobuf.dev/programming-guides/style/#:~:text=The%20zero%20value%20enum%20should,is%20the%20first%20enum%20value.
