### ISSUE TITLE
Generate code using the API.

### ISSUE THREAD

**Issue by lihengling** [danielgtaylor/python-betterproto#638]
### Summary

I want to use the API to generate code instead of generating it through a plugin

### What is the feature request for?

The core library

### The Problem

Currently, I see that betterproto only offers a plugin-based generation method. 
`   data = b""
    request = CodeGeneratorRequest()
    request.parse(data)`
I have read the source code and need to construct the byte stream data for data, which is very difficult for me. Could you provide a simpler method for generating code using the API?

### The Ideal Solution

such：
`output = generate_code_with_proto(proto_file: Path)`

**Comment by Gobot1234** [comment]
This is fixed by #165

**Comment by lihengling** [comment]
> This is fixed by #165

Thank you very much; using protobuf_parser has solved my problem very well.
