### ISSUE TITLE
Add black to build pipeline and readme

### ISSUE THREAD

**Issue by boukeversteegh** [danielgtaylor/python-betterproto#65]
As @nat-n suggested, enforcing [black](https://pypi.org/project/black/) as a validation step in the pipeline would reduce the number of merge-conflicts, and make sure that all contributors are aware that this project requires the use of black.

We could also mention it in the readme, or keep the readme short and let contributors find out after pushing

I prefer mentioning it.. as before black, i did spend some time formatting my code, which turned out to be a wasted effort

**Comment by nat-n** [comment]
Yip, it should be in the readme too.

**Comment by nat-n** [comment]
It would also be good to rename `template.py` to something like `template.py.j2` since that fact that it looks like a python file but isn't really causes confusion for black and certain other build tools (looking at you rpmbuild).

**Comment by nat-n** [comment]
Addressed in PR #72
