### ISSUE TITLE
Invitation link to Discord

### ISSUE THREAD

**Issue by vegarab** [danielgtaylor/python-betterproto#650]
### Summary

Slack is no longer used, link to Discord has expired

### What is the feature request for?

The documentation

### The Problem

The README link to Slack links to an archived Slack workspace. The link to Discord in the Slack workspace has expired. Ther is no way to join the Discord community.

### The Ideal Solution

Please share a valid invitation link to Discord, if this community is still active. Thanks.

**Comment by Gobot1234** [comment]
Would you mind opening a pr to replace it with https://discord.gg/DEVteTupPb in the readme and docs
