### ISSUE TITLE
Recursive message support

### ISSUE THREAD

**Issue by firdaus** [danielgtaylor/python-betterproto#74]
I am working on implementing a GRPC client which has a message such as this:

```
message Failure {
    ...
    Failure cause = 4;
    ...
}
```

Unfortunately it seems like betterproto attempts to build an object graph for this and this results in the following error:

```
RecursionError: maximum recursion depth exceeded while calling a Python object
```

I was wondering whether the project is planning on supporting this. 

My plan in the short run is to just fork betterproto for my project and not set a default value for sub-messages in `_get_field_default`. 

If the maintainers have a better approach to fixing this I would gladly offer my time in submitting a PR for it.

**Comment by boukeversteegh** [comment]
Thank you @firdaus for your report!

What would help for us, if you could make a PR to add a failing test-case for the scenario.

Please have a look at [betterproto/tests/README.md](https://github.com/danielgtaylor/python-betterproto/tree/master/betterproto/tests)

In short, create a new folder in `inputs` with the `proto` and `json` file, and add them to the xfail-list in `tests/inputs/config.py`

I personally think this should be supported. We have a lot of major bugs to fix still, so can't promise how quickly this will get implemented as we are a small number of voluntary contributors.

Let us know if you'd like any help~ we are on slack at https://betterproto.slack.com/

**Comment by jameslan** [comment]
I think this is duplicate with #13

**Comment by boukeversteegh** [comment]
> I think this is duplicate with #13

Looks like that indeed! The other issue shows an indirect recursion, whereas this one is an immediate recursion.

Solving one will solve both, most likely
