### ISSUE TITLE
Slack chat is invite only?

### ISSUE THREAD

**Issue by jhowarth** [danielgtaylor/python-betterproto#85]
Hey folks,

I'm looking to get involved with betterproto development and tried to join slack. It seems like it is invite only though? Is there a way to get an invite? Is there a public slack people can easily join?

This is the link I tried https://betterproto.slack.com/

<img width="758" alt="Screen Shot 2020-06-09 at 3 29 40 PM" src="https://user-images.githubusercontent.com/70012/84207352-0ece2b00-aa66-11ea-9ace-fdf7309103b7.png">

**Comment by boukeversteegh** [comment]
Public invite link now posted in readme. Feel free to join!
